name: "your-project-name"

services:
  project-db:
    image: postgres:18.1
    restart: always
    environment:
      - POSTGRES_DB=your-db-name
      - POSTGRES_USER=your-db-user
      - POSTGRES_PASSWORD=your-db-password
    ports:
      - "5432:5432"
    networks:
      - prisma-dev-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U your-db-user -d your-db-name" ]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 5s
    volumes:
      - postgres_data_your-project-name_dev:/var/lib/postgresql
    command: postgres -c listen_addresses=*
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  server:
    depends_on:
      project-db:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://your-db-user:your-db-password@project-db:5432/your-db-name?schema=public
    networks:
      - prisma-dev-network
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    develop:
      watch:
        - action: sync
          path: ./src
          target: "/usr/src/app/src"
        - action: sync
          path: ./prisma
          target: "usr/src/app/prisma"
        - action: sync
          path: ./tsconfig.json
          target: /usr/src/app/tsconfig.json
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./Dockerfile.dev

networks:
  prisma-dev-network:
volumes:
  postgres_data_your-project-name_dev:
